wip: Reject overlapping disruptions
criteo/node-disruption-controller pull request #49
Opened 2023-12-05 08:34 UTC by komuta

2023-12-05 11:31 UTC, komuta commented
Tests are incoming

2023-12-05 14:59 UTC, Lqp1 requested changes

2023-12-05 14:59 UTC, Lqp1 commented on internal/controller/nodedisruption_controller.go
> +				return true, ndr.GenerateRejectedStatus(fmt.Sprintf(`Selected node(s) overlap with another disruption: ”%s"`, otherDisruption.Name)), nil
This block is executed even if the flag `RejectOverlappingDisruption` is not set, no ? am I missing something?

2023-12-06 16:00 UTC, geobeau commented
You should add e2e test (or unittest but there are no places where we mock a client). I can help you set it up if you want

2023-12-06 16:01 UTC, geobeau requested changes

2023-12-07 09:27 UTC, komuta commented on internal/controller/nodedisruption_controller.go
> +			if otherDisruptedNodes.Intersection(disruptedNodes).Len() > 0 {
Sure, but could you elaborate a bit about the rational? Is it because of the additional requests to k8s api?

2023-12-07 12:47 UTC, Lqp1 approved these changes
looks good on my side but I'll let you finish regarding the last unresolved conversation with @geobeau

2023-12-11 09:47 UTC, Lqp1 approved these changes

2023-12-11 13:08 UTC, geobeau approved these changes

2023-12-11 20:18 UTC, merged